name: Deploy ADF to Azure

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v2.2.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ADF changes
        uses: Azure/data-factory-deploy-action@v1.2.5
        with:
          resourceGroupName: azure-project-naman
          dataFactoryName: df-azure-project-naman
          armTemplatePath: './ARMTemplateForFactory.json'
          armTemplateParametersPath: './ARMTemplateParametersForFactory.json'
